feat: add entities:list command
nuance-communications/mix-cli pull request #21
Opened 2022-07-05 17:24 UTC by grof

2022-07-11 14:21 UTC, oliver-daniel requested changes

2022-07-11 14:21 UTC, oliver-daniel commented on src/commands/entities/list.ts
> +      const [type] = Object.keys(entity)
I left a similar comment in #20 regarding this logic of getting the first key, and then looking up the value. Is this operation "safe" in terms of ordering? I wonder if there's a more idiomatic way to handle this.

2022-07-11 18:39 UTC, grof commented on src/mix/api/entities-types.ts
> +export type EntitiesListParams = Expand<EntitiesListPathParams & EntitiesListSearchParams>
Without the Expand, VSCode does not show useful information in Intellisense. Not a TypeScript pro but that worked.

2022-07-12 15:59 UTC, oliver-daniel approved these changes
Looks good.

2022-07-12 17:14 UTC, merged

2022-07-12 17:17 UTC, grof commented
:tada: This PR is included in version 1.4.0-beta.2 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@nuance-mix/mix-cli/v/1.4.0-beta.2)
- [GitHub release](https://github.com/nuance-communications/mix-cli/releases/tag/v1.4.0-beta.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-09-19 21:30 UTC, grof commented
:tada: This PR is included in version 3.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@nuance-mix/mix-cli/v/3.0.0-beta.1)
- [GitHub release](https://github.com/nuance-communications/mix-cli/releases/tag/v3.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: